services:
  spark-master:
    container_name: spark-master
    image: bitnami/spark:3.5.1
    ports:
      - "8081:8080"
      - "7077:7077"
    expose:
      - 8081
      - 7077
    restart: always
    volumes:
      - spark-binaries:/opt/bitnami/spark
      - spark-java:/opt/bitnami/java
      - spark-common:/opt/bitnami/common
      - ./data:/opt/airflow/data
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    networks:
      - airflow
    
  spark-worker-1:
    container_name: spark-worker-1
    image: bitnami/spark:3.5.1
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - spark-binaries:/opt/bitnami/spark
      - spark-java:/opt/bitnami/java
      - spark-common:/opt/bitnami/common
      - ./data:/opt/airflow/data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    networks:
      - airflow

  spark-worker-2:
    container_name: spark-worker-2
    image: bitnami/spark:3.5.1
    depends_on:
      - spark-master
    ports:
      - "8083:8082"
    volumes:
      - spark-binaries:/opt/bitnami/spark
      - spark-java:/opt/bitnami/java
      - spark-common:/opt/bitnami/common
      - ./data:/opt/airflow/data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    networks:
      - airflow

volumes:
  spark-binaries:
  spark-java:
  spark-common:

networks:
  airflow:
    driver: bridge